  
name: pull_request_workflow
on: pull_request
jobs:
  code-analysis-tests-compile:
    name: Code Analysis + Tests + Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Install packages
        run:
          flutter pub get
      - name: Code Analysis
        run: 
          flutter analyze
      - name: Tests
        run:
          flutter test
      - name: Compile
        run: |
          flutter build aot